services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    MLukman\SecurityHelperBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    MLukman\SecurityHelperBundle\Authentication\:
        resource: '../src/Authentication/'

    MLukman\SecurityHelperBundle\Authorization\:
        resource: '../src/Authorization/'

    MLukman\SecurityHelperBundle\Command\:
        resource: '../src/Command/'

    MLukman\SecurityHelperBundle\Util\:
        resource: '../src/Util/'

imports:
    - resource: services/
